# Numpy Exercises

Here we will learn basic step by step example of Numpy

By - Abhishek Anand - abhishekanand25[at]googlemail[dot}com

# First Import Numpy library as np

In [2]:
import numpy as np

# Creating array of 10 zero and 10 one

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Creating array of ten 5 or ten 8

In [9]:
np.ones(10) * 10
(np.ones(12) * 5).reshape(3,4)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [14]:
mat = np.arange(5,25)
matn = mat.reshape(5,4)
matn

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

# Run below example separately in your notepad

In [19]:
a = matn[1:3,1:4]
a

array([[10, 11, 12],
       [14, 15, 16]])

In [21]:
b = matn[3,3]
b

20

# Sum,std, mean of all values in matn 

In [23]:
matn

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [24]:
np.sum(matn)

290

In [25]:
mat.sum()

290

In [26]:
np.std(matn)

5.766281297335398

In [27]:
matn.std()

5.766281297335398